# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'splash_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SplashScreen(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen")
        SplashScreen.setWindowModality(QtCore.Qt.ApplicationModal)
        SplashScreen.resize(423, 185)
        SplashScreen.setAutoFillBackground(False)
        SplashScreen.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        SplashScreen.setDocumentMode(False)
        SplashScreen.setDockNestingEnabled(False)
        SplashScreen.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(SplashScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 60, 201, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.splash_label = QtWidgets.QLabel(self.centralwidget)
        self.splash_label.setGeometry(QtCore.QRect(60, 50, 64, 81))
        self.splash_label.setText("")
        self.splash_label.setPixmap(QtGui.QPixmap("resources/shopping.png"))
        self.splash_label.setObjectName("splash_label")
        self.label_footer1 = QtWidgets.QLabel(self.centralwidget)
        self.label_footer1.setGeometry(QtCore.QRect(150, 90, 251, 13))
        self.label_footer1.setObjectName("label_footer1")
        self.label_footer2 = QtWidgets.QLabel(self.centralwidget)
        self.label_footer2.setGeometry(QtCore.QRect(150, 100, 251, 14))
        self.label_footer2.setObjectName("label_footer2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(130, 60, 16, 61))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        SplashScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(SplashScreen)
        QtCore.QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QtCore.QCoreApplication.translate
        SplashScreen.setWindowTitle(_translate("SplashScreen", "Управление филиалами"))
        self.label.setText(_translate("SplashScreen", "Управление филиалами в отчетах"))
        self.label_footer1.setText(_translate("SplashScreen", "Департамент мастер-данных и отчетности"))
        self.label_footer2.setText(_translate("SplashScreen", "Офис прогнозирования © 2021"))
